name: Test cron env on multiple OSes via Docker

on:
  workflow_dispatch:

jobs:
  cron-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        image:
          - ubuntu:22.04
          - debian:bullseye
          - alpine:3.18
          - centos:7
          - centos:stream9
    name: ${{ matrix.image }}
    
    steps:
      - name: Checkout (dummy)
        uses: actions/checkout@v4

      - name: Run container and extract cron env
        run: |
          set -eux

          IMAGE=${{ matrix.image }}
          CONTAINER=cron-test

          # 準備スクリプト
          cat <<'EOF' > setup-cron.sh
          #!/bin/sh
          set -eux
          
          # cron のインストール（ディストリごとに異なる）
          if command -v apt-get >/dev/null 2>&1; then
            apt-get update && apt-get install -y cron
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache dcron
          elif command -v yum >/dev/null 2>&1; then
            yum install -y cronie
          fi

          echo "* * * * * env > /tmp/hoge.txt" > /etc/crontab
          chmod 600 /etc/crontab

          # cron 起動
          if command -v crond >/dev/null 2>&1; then
            crond
          else
            service cron start || /etc/init.d/cron start || cron
          fi
          sleep 65
          EOF

          chmod +x setup-cron.sh

          # コンテナ起動・実行
          docker run --rm -v $PWD:/host --name $CONTAINER $IMAGE /host/setup-cron.sh

      - name: Show env from cron
        run: |
          echo "::group::Dump cron env output from ${{ matrix.image }}"
          cat ./tmp/hoge.txt || echo "env not found"
          echo "::endgroup::"
